name: mcpelauncher-thesonicmaster
base: core18
version: '20210727'
license: GPL-3.0
summary: Minecraft Bedrock Linux launcher with license error fixed.
description: |
  This is The Sonic Master's fork of the Minecraft Bedrock Launcher
  (mcpelauncher), which fixes the license error. For more information, see
  https://mcpelauncher.thesonicmaster.net
architectures:
  - build-on: amd64
    run-on: amd64
grade: stable
confinement: strict
icon: snap/gui/icon.png
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
environment:
  ALWAYS_USE_PULSEAUDIO: '1'
apps:
  mcpelauncher-thesonicmaster:
    extensions:
      - kde-neon
    common-id: io.mrarm.mcpelauncher
    command-chain:
      - snap/command-chain/alsa-launch
    command: usr/bin/mcpelauncher-ui-qt
    desktop: usr/share/applications/mcpelauncher-ui-qt.desktop
    plugs:
      - alsa
      - audio-playback
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - network-bind
      - network-observe
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
    stage:
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdnsfile*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjack*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulse*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamplerate*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libspeex*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbis*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
  mcpelauncher-thesonicmaster:
    after:
      - alsa-mixin
    source: https://downloads.sourceforge.net/mcpelauncher-thesonicmaster/sources/mcpelauncher-thesonicmaster-20210727.tar.xz
    plugin: cmake
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    build-packages:
      - clang-10
      - gettext
      - libcurl4-openssl-dev
      - libegl1-mesa-dev
      - libprotobuf-dev
      - libssl-dev
      - libudev-dev
      - libuv1-dev
      - libxi-dev
      - libzip-dev
      - ninja-build
      - protobuf-compiler
      - texinfo
      - wget
    stage-packages:
      - lib32stdc++6
      - libcurl4
      - libprotobuf10
      - libuv1
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      # We need a newer version of cmake, otherwise the launcher won't compile.
      wget -nc https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0-linux-x86_64.tar.gz
      tar --skip-old-files -xf cmake-3.20.0-linux-x86_64.tar.gz
      cmake=$SNAPCRAFT_PART_SRC/cmake-3.20.0-linux-x86_64/bin/cmake
      cmake_options="-DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_ROOT_PATH='/snap/kde-frameworks-5-core18-sdk/current;/snap/kde-frameworks-5-core18/current' -Wno-dev -G Ninja"
      cd msa
      mkdir -p build && cd build
      CC=clang-10 CXX=clang++-10 CFLAGS='-O3' CXXFLAGS='-O3' $cmake -DENABLE_MSA_QT_UI=ON $cmake_options ..
      ninja
      DESTDIR=$SNAPCRAFT_PART_INSTALL ninja install
      cd ../../mcpelauncher
      mkdir -p build && cd build
      CC=clang-10 CXX=clang++-10 CFLAGS='-O3' CXXFLAGS='-O3' $cmake -DENABLE_QT_ERROR_UI=OFF -DJNI_USE_JNIVM=ON $cmake_options ..
      ninja
      DESTDIR=$SNAPCRAFT_PART_INSTALL ninja install
      cd ../../mcpelauncher-ui
      mkdir -p build && cd build
      CC=clang-10 CXX=clang++-10 CFLAGS='-O3' CXXFLAGS='-O3' $cmake -DLAUNCHER_VERSION_CODE="SNAP" $cmake_options ..
      ninja
      DESTDIR=$SNAPCRAFT_PART_INSTALL ninja install
      # Strip executables to free up some space.
      strip --strip-all $SNAPCRAFT_PART_INSTALL/usr/bin/*
      # Fix icon display for snap package.
      sed -i 's/Icon=mcpelauncher-ui-qt/Icon=\/usr\/share\/pixmaps\/mcpelauncher-ui-qt.png/' $SNAPCRAFT_PART_INSTALL/usr/share/applications/mcpelauncher-ui-qt.desktop
